### ISSUE TITLE
New name:  Side View

### ISSUE THREAD

**Issue by wresuolc** [mozilla/tab-split-2#102]
New approved name:  Side View

Please make changes as appropriate.  /cc @jbuck

**Comment by fzzzy** [comment]
Sweet.

**Comment by wresuolc** [comment]
@jbuck -- we're going to rename this repository.  Will you change the auto-building scripts to point to the new location?

**Comment by jbuck** [comment]
Yep! just let me know when it's changed

**Comment by fzzzy** [comment]
@jbuck It has changed now.

**Comment by jbuck** [comment]
I've updated the build job now
