### ISSUE TITLE
Tabs with no icon don't display well on the homepage

### ISSUE THREAD

**Issue by ianb** [mozilla/tab-split-2#31]
Example: about:newtab

**Comment by ianb** [comment]
To make things look OK I think we need a replacement favicon for those cases when there isn't one.

**Comment by pdehaan** [comment]
This works for Nightly, haven't tried it in Release/Beta/DevEd channels yet:

```js
    let image = document.createElement("img");
    image.src = tab.favIconUrl || "chrome://branding/content/icon32.png";
    image.width = 16;
```

![icon32](https://user-images.githubusercontent.com/557895/36874776-0d35748a-1d62-11e8-8b5e-0049ce74a564.png)

Probably wouldn't catch cases where there is a `favIconUrl` defined, but it's invalid or 404s. You could _possibly_ use something hacky like `<img src="blah" onerror="handle404ErrorCaseHere();" />`, but that seems ill-advised.
