### ISSUE TITLE
Add === warning

### ISSUE THREAD

**Issue by ianb** [mozilla/tab-split-2#45]
Per [this comment](https://github.com/mozilla/tab-split-2/pull/44/files#r171682482)

**Comment by pdehaan** [comment]
I added the ESLint rule in PR #44 https://github.com/mozilla/tab-split-2/blob/0457b1cb316d5f7c502db80079efd4bd7e1950aa/.eslintrc.js#L18

But I can fix those 4 warnings in about 4 seconds if you want a PR for it.

**Comment by ianb** [comment]
sure!
