### ISSUE TITLE
Copy the version number from package.json to addon/manifest.json during the build

### ISSUE THREAD

**Issue by fzzzy** [mozilla/tab-split-2#48]
Right now, they have to manually be kept in sync (and are not in sync)

**Comment by lmorchard** [comment]
FWIW, in Snooze Tabs and ThemesRFun, I kept finding further overlap between package.json and manifest.json. So, I fell back to keeping the unique bits of manifest.json inside an [`extensionManifest` property of package.json](https://github.com/mozilla/ThemesRFun/blob/master/package.json#L93). Then, [the build process creates the manifest](https://github.com/mozilla/ThemesRFun/blob/master/webpack.extension.js#L35) from the combined data.
