### ISSUE TITLE
Support windows in npm scripts

### ISSUE THREAD

**Issue by pdehaan** [mozilla/tab-split-2#52]
via archived https://github.com/mozilla/tab-split/issues/54

> When doing things with directories in npm scripts, it is best to use something like [**mkdirp**](https://www.npmjs.com/package/mkdirp) for portability across UNIX and Windows.
>
> [**cross-env**](https://www.npmjs.com/package/cross-env) is also helpful for setting env variables

**Comment by pdehaan** [comment]
I can never remember if we have any Windows users on the team that this may block. I'm guessing most of us are currently running macOS/Linux and we could tag this as **good first issue** and leave until post-release.

Only potential issues I see so far are:

https://github.com/mozilla/tab-split-2/blob/d72d65b65647b5577336d86c0dfd3881142d15e3/package.json#L33-L37

We could replace `mkdir -p` with [**mkdirp**](http://npm.im/mkdirp), as mentioned above.
`cp` can be replaced with [**ncp**](http://npm.im/ncp).
The **mustache** script pipes output using the `>` operator, which I assume is supported by Windows' version of Bash/Powershell/Cygwin.

I have no idea what an OS-agnostic version of `ls -t1 web-ext-artifacts | head -n 1` is, apart from using [**rimraf**](http://npm.im/rimraf) to just delete the ./web-ext-artifacts directory before each build.

**Comment by ianb** [comment]
I'm assuming Windows users are now using Bash for Windows, in which case this should all work fine, I think?

**Comment by johngruen** [comment]
@pdehaan i'm being bullied into this by @clouserw and @ianb
