### ISSUE TITLE
The Feedback button wrongly overlaps the "Current tabs" list when the window is vertically resized

### ISSUE THREAD

**Issue by Softvision-CristinaBadescu** [mozilla/tab-split-2#69]
[Affected versions]:
- Firefox 58.0.2 and up
- Tab Split 2 0.2.0

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have a clean Firefox profile with the latest Tab Split 2 v0.2.0 installed.
- Have at least 4 tabs open.
- Have Tab Split sidebar open.

[Steps to reproduce]:
1. Open Firefox browser with the profile from prerequisites.
2. Vertically resize the window until "Recent Splits" section is not visible.
3. Scroll down and observe the right bottom of the sidebar.

[Expected result]:
- The "Feedback" button is displayed.

[Actual result]:
- The "Feedback" button overlaps the "Current Tabs" list.

[Notes]:
- This issue is reproducible if you diagonally resize the window or if you resize the sidebar to its minimum width.
- Also, when you hover the "Feedback" button, it is partially visible.
- Here is a screen recording with this issue:
![tab split 2 - feedback icon](https://user-images.githubusercontent.com/31244235/37201583-c8adf492-2390-11e8-8afb-f74e91b8ef9c.gif)

**Comment by SoftVision-CiprianMuresan** [comment]
The issue is no longer reproducible on the latest version of Tab Split on Windows 10 x64, Mac 10.13.3 and Arch Linux. The Feedback button is now always on top.
