### ISSUE TITLE
The "Current Tabs" list does not update accordingly when a tab is closed

### ISSUE THREAD

**Issue by Softvision-CristinaBadescu** [mozilla/tab-split-2#70]
[Affected versions]:
- Firefox 58.0.2 and up
- Tab Split 2 0.2.0

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have a clean Firefox profile with the latest Tab Split 2 v0.2.0 installed.
- Have at least 2 tabs open.
- Have Tab Split sidebar open.

[Steps to reproduce]:
1. Open Firefox browser with the profile from prerequisites.
2. Close one tab and observe the "Current Tabs" list.

[Expected result]:
- The closed tab is no longer displayed in the list.

[Actual result]:
- The previously closed tab is still displayed.

[Notes]:
- The list updates only after another action is performed, such as closing another tab, open another tab or refreshing the window.
- Here is a screen recording with this issue:
![tab split 2 - current tabs list](https://user-images.githubusercontent.com/31244235/37204950-8b91df82-239b-11e8-9858-4f5bed9c6cbd.gif)

**Comment by ianb** [comment]
Apparently the 50ms delay I had in the code to re-fetch the tab list still wasn't enough to see closes. I've added another 300ms delay in #78

**Comment by SoftVision-CiprianMuresan** [comment]
The issue is no longer reproducible on the latest version of Tab Split on Windows 10 x64, Mac 10.13.3 and Arch Linux.
