### ISSUE TITLE
Sites like medium.com break out of the iframe using JavaScript

### ISSUE THREAD

**Issue by Softvision-CristinaBadescu** [mozilla/tab-split-2#72]
[Affected versions]:
- Firefox 58.0.2 and up
- Tab Split 2 0.2.0

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have a clean Firefox profile with the latest Tab Split 2 v0.2.0 installed.

[Steps to reproduce]:
1. Open Firefox browser with the profile from prerequisites and navigate to https://medium.com/.
2. Open the "Tab Split" sidebar and click the "Medium" tab from the "Current Tabs" section.
3. Observe the sidebar's UI elements.

[Expected result]:
- In the top of the sidebar the "Home" & "Refresh" buttons are displayed and at the bottom the "Request desktop site" checkbox is displayed.

[Actual result]:
- The sidebar UI elements are displayed only for a brief moment and afterwards they disappear.

[Notes]:
- Here is a screen recording with this issue:
![tab split 2 - medium lacks ui elements](https://user-images.githubusercontent.com/31244235/37210248-af5a1cc6-23b0-11e8-8009-07d7d179c052.gif)

**Comment by ianb** [comment]
Medium is using this (traditional) framebusting code: 

```js
if (window.top !== window.self) window.top.location = window.self.location.href;
```

I'm not sure if we have a good way of fixing this.

**Comment by johngruen** [comment]
I don't think we're going to solve this, but some remediation would be nice

**Comment by Softvision-CristinaBadescu** [comment]
This issue is no longer reproducible using Side View v0.2.0, on latest Firefox release 59.0.2, latest Nightly build 61.0a1 (2018-03-29), on Windows 10 x64, Mac 10.13.3 and Ubuntu 14.04 x64.
