### ISSUE TITLE
The "Home" and "Refresh" buttons' tooltips text are wrongly displayed only in lowercase letters

### ISSUE THREAD

**Issue by Softvision-CristinaBadescu** [mozilla/tab-split-2#75]
[Affected versions]:
- Firefox 58.0.2 and up
- Tab Split 2 0.2.0

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have a clean Firefox profile with the latest Tab Split 2 v0.2.0 installed.
- Have one website open in the Tab Split sidebar.

[Steps to reproduce]:
1. Open the Firefox browser with the profile from prerequisites.
2. Hover the "Home" sidebar's button and observe the text from its tooltip.
3. Hover the "Refresh" sidebar's button and observe the text from its tooltip.

[Expected result]:
Step 2: - "Home" text is displayed.
Step 3: - "Refresh" text is displayed.

[Actual result]:
Step 2 & Step 3 - The tooltips texts start with lowercase letters.

[Notes]:
- Here is a screen shot with this issue:
![home button](https://user-images.githubusercontent.com/31244235/37215762-8f7f8c9a-23c1-11e8-83ca-db0a937f48fd.png)
![refresh](https://user-images.githubusercontent.com/31244235/37215765-9175b3f8-23c1-11e8-89f2-4acca3b9f256.png)

**Comment by SoftVision-CiprianMuresan** [comment]
The issue is no longer reproducible on the latest version of Tab Split on Windows 10 x64, Mac 10.13.3 and Arch Linux.
