### ISSUE TITLE
Tab Split doesn't work in other windows, on Windows and Mac OS'es

### ISSUE THREAD

**Issue by Softvision-CristinaBadescu** [mozilla/tab-split-2#80]
[Affected versions]:
- Nightly 60.0a1
- Tab Split 2 0.2.0

[Affected Platforms]:
- All Windows
- All Mac

[Prerequisites]:
- Have a clean Firefox profile with the latest Tab Split 2 v0.2.0 installed.
- Have the Tab Split sidebar open.

[Steps to reproduce]:
1. Open the Firefox browser with the profile from prerequisites.
2. Open a new window and navigate to a website.
3. Click the "Open current tab in sidebar" toolbar button.
4. Observe the behavior.

[Expected result]:
- The page is loaded in the sidebar.

[Actual result]:
- The page is not loaded in the sidebar and the sidebar's Homepage UI is displayed.

[Regression]:
- I've managed to find a regression-window using the Mozregression tool. Here are the results:
Last good revision: 7433031c9274b8299c3e2d50613de74352684bc1
First bad revision: 95a6bd5b90452da6eee11eb8ee53ef80c91565c6
Pushlog: https://goo.gl/zAwV7D

From the pushlog it seems that bug #[1398713](https://bugzilla.mozilla.org/show_bug.cgi?id=1398713) has caused this issue.

[Notes]:
- This issue is also reproducible for the "Open in sidebar" option from the tab strip context menu and for the "Open link in sidebar" context menu option.
- It seems that bug [1398713](https://bugzilla.mozilla.org/show_bug.cgi?id=1398713) has caused regressions in other experiments too (bug [741](https://github.com/mozilla/notes/issues/741)). Work was also done on Firefox's side too (bug [1443749](https://bugzilla.mozilla.org/show_bug.cgi?id=1443749)).
- Here is a screen recording with this issue:
![tab split 2 - does not work in other windows](https://user-images.githubusercontent.com/31244235/37284114-0d4ed1d8-2603-11e8-9613-b765c5176acf.gif)

**Comment by ianb** [comment]
@mixedpuppy is working on [Bug 1443749](https://bugzilla.mozilla.org/show_bug.cgi?id=1443749) as a fix.

**Comment by mixedpuppy** [comment]
You'll want to follow Bug 1445080

**Comment by mixedpuppy** [comment]
Bug 1445080 should fix this, if someone can verify with this extension.

**Comment by SoftVision-CiprianMuresan** [comment]
The issue is no longer reproducible on the latest Nightly (61.0a1) on Windows 10 x64 and Mac 10.13.3.
