### ISSUE TITLE
The sidebar wrongly becomes blank for a second after you send links or tabs to it

### ISSUE THREAD

**Issue by Softvision-CristinaBadescu** [mozilla/tab-split-2#81]
[Affected versions]:
- Nightly 60.0a1
- Tab Split 2 0.2.0

[Affected Platforms]:
- All Windows
- All Mac

[Prerequisites]:
- Have a clean Firefox profile with the latest Tab Split 2 v0.2.0 installed.
- Have the Tab Split sidebar open.

[Steps to reproduce]:
1. Open the Firefox browser with the profile from prerequisites and navigate to a website.
2. Click the "Open current tab in sidebar" toolbar button and observe the behavior.

[Expected result]:
- The page is displayed in the sidebar.

[Actual result]:
- The sidebar becomes blank for a second and afterwards the site is loaded.

[Regression]:
- I've managed to find a regression-window using the Mozregression tool. Here are the results:
Last good revision: 7433031c9274b8299c3e2d50613de74352684bc1
First bad revision: 95a6bd5b90452da6eee11eb8ee53ef80c91565c6
Pushlog: https://goo.gl/zAwV7D

From the pushlog it seems that bug #[1398713](https://bugzilla.mozilla.org/show_bug.cgi?id=1398713) has caused this issue.

[Notes]:
- This issue is also reproducible for the "Open in sidebar" option from the tab strip context menu and for the "Open link in sidebar" context menu option.
- This issue has the same pushlog result as #80.
- It seems that bug [1398713](https://bugzilla.mozilla.org/show_bug.cgi?id=1398713) has caused regressions in other experiments too (bug [741](https://github.com/mozilla/notes/issues/741)). Work was also done on Firefox's side too (bug [1443749](https://bugzilla.mozilla.org/show_bug.cgi?id=1443749)).
- Here is a screen recording with this issue:
![tab split 2 - blank sidebar for a second](https://user-images.githubusercontent.com/31244235/37331646-202a6b8c-26ad-11e8-907e-51bdf33506cd.gif)

**Comment by SoftVision-CiprianMuresan** [comment]
The issue is no longer reproducible on the latest version of Tab Split on Windows 10 x64, Mac 10.13.3 and Arch Linux. Now a loading page is displayed instead.
